//! Input schema for the token-optimized YAML payload generated by an LLM.
//!
//! The LLM emits a flat, minimal YAML document. This module defines the
//! corresponding serde structs and provides a [`DiagramPayload::from_yaml`]
//! constructor that validates the input at the boundary.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Top-level diagram payload
// ---------------------------------------------------------------------------

/// Root structure of the token-optimized YAML payload produced by an LLM.
///
/// # Example
///
/// ```yaml
/// diagram_type: flowchart
/// theme: aws_light
/// nodes:
///   - id: n1
///     label: "API Gateway"
///     type: proxy
///   - id: n2
///     label: "User Database"
///     type: database
///     metadata: "Stores encrypted user credentials."
/// edges:
///   - from: n1
///     to: n2
///     label: "queries"
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DiagramPayload {
    /// Optional human-readable title for the entire diagram.
    /// Rendered as a prominent title banner at the top of the canvas.
    #[serde(default, alias = "name")]
    pub title: Option<String>,

    /// Optional diagram description or subtitle.
    #[serde(default, alias = "subtitle", alias = "desc")]
    pub description: Option<String>,

    /// Logical diagram category (e.g. `flowchart`, `architecture`, `sequence`, `graph`).
    #[serde(default = "default_diagram_type", alias = "type", alias = "kind")]
    pub diagram_type: String,

    /// Optional visual theme: `standard` (elevated white cards) or `dark` (slate-900).
    #[serde(default)]
    pub theme: Option<String>,

    /// Optional flow direction override: `tb` (top-to-bottom) or `lr` (left-to-right).
    /// Accepts aliases: `TB`, `LR`, `horizontal`, `vertical`.
    #[serde(default, alias = "flow", alias = "layout_direction")]
    pub direction: Option<String>,

    /// Optional vertical spacing between ranks in pixels.
    #[serde(default)]
    pub rank_spacing: Option<u32>,

    /// Optional horizontal spacing between sibling nodes in pixels.
    #[serde(default)]
    pub node_spacing: Option<u32>,

    /// Optional canvas-level configuration (margin, background).
    #[serde(default)]
    pub canvas: Option<CanvasConfig>,

    /// Optional spacing configuration, grouping the individual spacing knobs.
    /// `rank_spacing`/`node_spacing` above take priority over `spacing.rank`/`spacing.node`
    /// when both are set — they exist for backward compatibility with earlier payloads.
    #[serde(default)]
    pub spacing: Option<SpacingConfig>,

    /// When `true`, edges are annotated with a sequence badge (1, 2, 3, …) in the order
    /// they're declared (or per-edge `step` override), so a reader can trace the flow.
    #[serde(default)]
    pub numbered: Option<bool>,

    /// Named, reusable node style presets. A node opts in via `class: <name>`; any field the
    /// node doesn't already set explicitly is filled in from the preset. Existing keys are
    /// never overwritten by a preset — this exists to de-duplicate repeated per-node styling,
    /// not to act as a second source of truth.
    #[serde(default, alias = "node_classes", alias = "component_styles")]
    pub node_styles: HashMap<String, NodeStyleOverride>,

    /// Named, reusable edge style presets — same resolution rules as [`node_styles`].
    #[serde(default, alias = "edge_classes", alias = "connector_styles")]
    pub edge_styles: HashMap<String, EdgeStyleOverride>,

    /// Ordered list of node definitions.
    #[serde(default)]
    pub nodes: Vec<NodeDef>,

    /// Ordered list of directed edge definitions.
    #[serde(default)]
    pub edges: Vec<EdgeDef>,

    /// Optional list of visual group / swimlane containers.
    #[serde(default, alias = "containers", alias = "swimlanes")]
    pub groups: Vec<GroupDef>,
}

/// Overall flow direction of the diagram, as resolved from the YAML payload.
///
/// Deliberately schema-local (rather than reusing `rdg_layout::LayoutDirection`) so that
/// `rdg-schema` has no dependency on `rdg-layout`; the CLI maps this to the layout
/// engine's own direction type.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    /// Top to Bottom (hierarchical DAG standard).
    TopToBottom,
    /// Left to Right (horizontal pipelines, sequence flows).
    LeftToRight,
}

fn default_diagram_type() -> String {
    "flowchart".to_owned()
}

fn default_node_type() -> String {
    "default".to_owned()
}

impl DiagramPayload {
    /// Parse a YAML string into a [`DiagramPayload`].
    ///
    /// # Errors
    ///
    /// Returns an error if the YAML is malformed or cannot be parsed.
    pub fn from_yaml(input: &str) -> Result<Self> {
        serde_yaml::from_str(input).context("failed to deserialize YAML diagram payload")
    }

    /// Resolves the optional direction string into a [`Direction`].
    ///
    /// This is a schema-local type (rather than `rdg_layout::LayoutDirection`) so that
    /// `rdg-schema` does not need to depend on `rdg-layout`; callers map it to the
    /// layout engine's own direction type.
    pub fn resolved_direction(&self) -> Option<Direction> {
        self.direction
            .as_deref()
            .map(|d| match d.trim().to_ascii_lowercase().as_str() {
                "lr" | "left_to_right" | "horizontal" | "h" => Direction::LeftToRight,
                _ => Direction::TopToBottom,
            })
    }

    /// Returns the resolved canonical diagram category.
    /// Values: `"flowchart"`, `"architecture"`, `"sequence"`, `"er"`, `"class"`, `"state"`.
    pub fn resolved_diagram_type(&self) -> &str {
        match self.diagram_type.to_ascii_lowercase().trim() {
            "seq" | "sequence" | "uml_sequence" => "sequence",
            "er" | "erd" | "database" | "schema" | "relational" => "er",
            "class" | "uml_class" | "oop" => "class",
            "state" | "state_machine" | "fsm" => "state",
            "arch" | "architecture" | "system" => "architecture",
            _ => "flowchart",
        }
    }

    /// Returns `true` when edges should be annotated with a flow sequence badge.
    pub fn is_numbered(&self) -> bool {
        self.numbered.unwrap_or(false)
    }

    /// Merges a node's `class` style preset (if any) into a copy of `node`.
    ///
    /// Fields the node already set explicitly are left untouched — a preset only fills in
    /// gaps, it never overrides an author's explicit choice. Unknown class names, or a node
    /// with no `class`, return `node` unchanged (cloned).
    pub fn effective_node(&self, node: &NodeDef) -> NodeDef {
        let mut merged = node.clone();
        let Some(class) = node.class.as_deref() else {
            return merged;
        };
        let Some(preset) = self.node_styles.get(class) else {
            return merged;
        };
        if merged.color.is_none() {
            merged.color = preset.color.clone();
        }
        if merged.technology.is_none() {
            merged.technology = preset.technology.clone();
        }
        if merged.language.is_none() {
            merged.language = preset.language.clone();
        }
        if merged.db_type.is_none() {
            merged.db_type = preset.db_type.clone();
        }
        if merged.icon.is_none() {
            merged.icon = preset.icon.clone();
        }
        if merged.width.is_none() {
            merged.width = preset.width;
        }
        if merged.height.is_none() {
            merged.height = preset.height;
        }
        if merged.provider.is_none() {
            merged.provider = preset.provider.clone();
        }
        if merged.style_extra.is_none() {
            merged.style_extra = preset.style_extra.clone();
        }
        merged
    }

    /// Merges an edge's `class` style preset (if any) into a copy of `edge`. Same
    /// gap-filling semantics as [`DiagramPayload::effective_node`].
    pub fn effective_edge(&self, edge: &EdgeDef) -> EdgeDef {
        let mut merged = edge.clone();
        let Some(class) = edge.class.as_deref() else {
            return merged;
        };
        let Some(preset) = self.edge_styles.get(class) else {
            return merged;
        };
        if merged.edge_style.is_none() {
            merged.edge_style = preset.edge_style.clone();
        }
        if merged.color.is_none() {
            merged.color = preset.color.clone();
        }
        if merged.width.is_none() {
            merged.width = preset.width;
        }
        if merged.line_style.is_none() {
            merged.line_style = preset.line_style.clone();
        }
        if merged.head.is_none() {
            merged.head = preset.head.clone();
        }
        if merged.tail.is_none() {
            merged.tail = preset.tail.clone();
        }
        if merged.style_extra.is_none() {
            merged.style_extra = preset.style_extra.clone();
        }
        merged
    }

    /// Returns a complete, production-ready reference YAML template.
    pub fn example_yaml() -> &'static str {
        EXAMPLE_YAML
    }

    /// Returns the JSON Schema (draft-07) specification for [`DiagramPayload`].
    pub fn json_schema() -> &'static str {
        JSON_SCHEMA
    }
}

impl Default for DiagramPayload {
    fn default() -> Self {
        Self {
            title: None,
            description: None,
            diagram_type: default_diagram_type(),
            theme: None,
            direction: None,
            rank_spacing: None,
            node_spacing: None,
            canvas: None,
            spacing: None,
            numbered: None,
            node_styles: HashMap::new(),
            edge_styles: HashMap::new(),
            nodes: Vec::new(),
            edges: Vec::new(),
            groups: Vec::new(),
        }
    }
}

// ---------------------------------------------------------------------------
// Canvas & spacing configuration
// ---------------------------------------------------------------------------

/// Canvas-level rendering configuration.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CanvasConfig {
    /// Outer margin in pixels around the whole diagram (replaces the built-in default).
    #[serde(default)]
    pub margin: Option<f64>,

    /// Canvas background color (e.g. `#f8fafc`). Overrides the theme default.
    #[serde(default, alias = "bg", alias = "fill")]
    pub background: Option<String>,
}

/// Grouped spacing configuration — an alternative to the flat `rank_spacing`/`node_spacing`
/// top-level fields for payloads that want every spacing knob in one place.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SpacingConfig {
    /// Vertical gap between ranks/layers in pixels.
    #[serde(default)]
    pub rank: Option<u32>,

    /// Horizontal gap between sibling nodes on the same rank in pixels.
    #[serde(default)]
    pub node: Option<u32>,

    /// Horizontal gap between adjacent group containers in pixels.
    #[serde(default)]
    pub group_gap_x: Option<f64>,

    /// Vertical gap between adjacent group containers in pixels.
    #[serde(default)]
    pub group_gap_y: Option<f64>,
}

// ---------------------------------------------------------------------------
// Group / Swimlane definition
// ---------------------------------------------------------------------------

/// Visual container grouping a set of related nodes.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupDef {
    /// Unique identifier for the group container.
    pub id: String,

    /// Label displayed in the group header.
    #[serde(alias = "title", alias = "name")]
    pub label: String,

    /// Optional accent color for container background/border (e.g. `#0284c7`).
    #[serde(default, alias = "border", alias = "fill", alias = "accent")]
    pub color: Option<String>,

    /// List of node IDs contained in this group.
    #[serde(default, alias = "members", alias = "node_ids")]
    pub nodes: Vec<String>,

    /// Optional programming language or tech stack for the container (e.g. `rust`, `go`, `python`).
    /// When specified or detected, member nodes sharing this stack do not display redundant icons.
    #[serde(default, alias = "lang")]
    pub language: Option<String>,

    /// Optional explicit brand or service icon for the group container header.
    #[serde(default)]
    pub icon: Option<String>,
}

impl GroupDef {
    /// Resolves the programming language for this container.
    pub fn resolved_language(&self) -> Option<String> {
        let explicit =
            rdg_icons::detect_language(self.language.as_deref(), None, &self.label, None);
        if explicit.is_some() {
            return explicit.map(|s| s.to_string());
        }
        // Check for common prefix patterns like "crates/" or "cargo/"
        let lower = self.label.to_ascii_lowercase();
        if lower.contains("crates/") || lower.contains("cargo") {
            return Some("rust".to_string());
        }
        None
    }

    /// Resolves the icon key for the container header.
    pub fn resolved_icon(&self) -> Option<String> {
        if let Some(i) = &self.icon {
            if !i.trim().is_empty() {
                return Some(i.trim().to_ascii_lowercase());
            }
        }
        if let Some(l) = self.resolved_language() {
            return Some(l);
        }
        None
    }
}

// ---------------------------------------------------------------------------
// Reusable style presets
// ---------------------------------------------------------------------------

/// A named, reusable set of node styling fields. See [`DiagramPayload::node_styles`].
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct NodeStyleOverride {
    #[serde(default, alias = "colour", alias = "stroke")]
    pub color: Option<String>,
    #[serde(default, alias = "tech", alias = "stack", alias = "framework")]
    pub technology: Option<String>,
    #[serde(default, alias = "lang")]
    pub language: Option<String>,
    #[serde(default, alias = "database_type", alias = "engine", alias = "db")]
    pub db_type: Option<String>,
    #[serde(default, alias = "logo", alias = "badge")]
    pub icon: Option<String>,
    #[serde(default)]
    pub width: Option<f64>,
    #[serde(default)]
    pub height: Option<f64>,
    #[serde(default, alias = "cloud")]
    pub provider: Option<String>,
    #[serde(default, alias = "drawio_style", alias = "extra_style")]
    pub style_extra: Option<String>,
}

/// A named, reusable set of edge styling fields. See [`DiagramPayload::edge_styles`].
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct EdgeStyleOverride {
    #[serde(default, alias = "style", alias = "type")]
    pub edge_style: Option<String>,
    #[serde(default, alias = "colour", alias = "stroke")]
    pub color: Option<String>,
    #[serde(default, alias = "stroke_width", alias = "thickness")]
    pub width: Option<f64>,
    #[serde(default, alias = "stroke_style", alias = "pattern")]
    pub line_style: Option<String>,
    #[serde(default, alias = "arrow_head", alias = "end_arrow")]
    pub head: Option<String>,
    #[serde(default, alias = "arrow_tail", alias = "start_arrow")]
    pub tail: Option<String>,
    #[serde(default, alias = "drawio_style", alias = "extra_style")]
    pub style_extra: Option<String>,
}

// ---------------------------------------------------------------------------
// Node definition
// ---------------------------------------------------------------------------

/// A single semantic node as emitted by the LLM.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NodeDef {
    /// Unique identifier used to reference this node in edges.
    pub id: String,

    /// Human-readable label rendered inside the shape.
    #[serde(default)]
    pub label: String,

    /// Alternative to `label`: primary title line.
    #[serde(default, alias = "name")]
    pub title: Option<String>,

    /// Optional subtitle line (rendered as muted text below the title).
    #[serde(default, alias = "sub_label", alias = "detail")]
    pub subtitle: Option<String>,

    /// Semantic type used to select the draw.io style (e.g. `proxy`, `database`).
    #[serde(
        rename = "type",
        alias = "node_type",
        alias = "kind",
        alias = "shape",
        default = "default_node_type"
    )]
    pub node_type: String,

    /// Optional free-text metadata (e.g. tooltip, annotation).
    #[serde(default, alias = "description", alias = "desc", alias = "tooltip")]
    pub metadata: Option<String>,

    /// Optional list of table columns (for ER diagrams) or class attributes/methods (for UML Class diagrams).
    #[serde(
        default,
        alias = "columns",
        alias = "attributes",
        alias = "members_list"
    )]
    pub fields: Vec<String>,

    /// Optional programming language used to code this component (e.g. `rust`, `go`, `python`, `typescript`).
    #[serde(default, alias = "lang", alias = "runtime", alias = "code")]
    pub language: Option<String>,

    /// Optional technology stack or framework subtitle (e.g. `Axum + Tokio`, `FastAPI`, `Spring Boot`).
    #[serde(default, alias = "tech", alias = "stack", alias = "framework")]
    pub technology: Option<String>,

    /// Optional database engine (e.g. `postgres`, `mysql`, `redis`, `mongodb`, `dynamodb`).
    #[serde(default, alias = "database_type", alias = "engine", alias = "db")]
    pub db_type: Option<String>,

    /// Optional icon override key (e.g. `rust`, `postgres`, `user`, `kafka`).
    #[serde(default, alias = "logo", alias = "badge")]
    pub icon: Option<String>,

    /// Optional custom accent/border color (e.g. `#ef4444`), overriding the semantic-type
    /// default color table for just this node.
    #[serde(default, alias = "colour", alias = "stroke", alias = "accent")]
    pub color: Option<String>,

    /// Optional explicit width in pixels, skipping automatic content-based sizing.
    #[serde(default)]
    pub width: Option<f64>,

    /// Optional explicit height in pixels, skipping automatic content-based sizing.
    #[serde(default)]
    pub height: Option<f64>,

    /// Optional cloud provider hint (`aws`, `gcp`, `azure`) steering icon/shape selection
    /// for provider-specific component types (e.g. a `function` node with `provider: aws`).
    #[serde(default, alias = "cloud")]
    pub provider: Option<String>,

    /// Optional named style preset to inherit from — see [`DiagramPayload::node_styles`].
    #[serde(default, alias = "preset", alias = "style")]
    pub class: Option<String>,

    /// Optional raw draw.io style fragment appended verbatim to the computed style string
    /// (e.g. `"opacity=60;glass=1;"`). draw.io-only — the SVG backend has no equivalent raw
    /// styling surface, so this field is ignored there.
    #[serde(default, alias = "drawio_style", alias = "extra_style")]
    pub style_extra: Option<String>,

    /// Optional URL. When set, the rendered shape becomes a clickable link (draw.io only).
    #[serde(default, alias = "url", alias = "href")]
    pub link: Option<String>,
}

impl Default for NodeDef {
    fn default() -> Self {
        Self {
            id: String::new(),
            label: String::new(),
            title: None,
            subtitle: None,
            node_type: default_node_type(),
            metadata: None,
            fields: Vec::new(),
            language: None,
            technology: None,
            db_type: None,
            icon: None,
            color: None,
            width: None,
            height: None,
            provider: None,
            class: None,
            style_extra: None,
            link: None,
        }
    }
}

impl NodeDef {
    /// Resolves the effective label for rendering.
    ///
    /// If `label` is non-empty, returns it.
    /// If `title` is supplied, combines `title` and optional `subtitle`.
    /// Otherwise falls back to `id`.
    pub fn resolved_label(&self) -> String {
        if !self.label.trim().is_empty() {
            return self.label.clone();
        }
        if let Some(t) = &self.title {
            if let Some(sub) = &self.subtitle {
                if !sub.trim().is_empty() {
                    return format!("{t}\n({sub})");
                }
            }
            return t.clone();
        }
        self.id.clone()
    }

    /// Returns the resolved list of fields (columns or class members).
    /// If `fields` is empty, checks if `label` contains `---` or markdown list lines.
    pub fn resolved_fields(&self) -> Vec<String> {
        if !self.fields.is_empty() {
            return self.fields.clone();
        }
        if self.label.contains("---") {
            let mut parts = self.label.split("---");
            let _title = parts.next();
            if let Some(rest) = parts.next() {
                return rest
                    .lines()
                    .map(|l| l.trim().trim_start_matches('-').trim())
                    .filter(|l| !l.is_empty())
                    .map(|s| s.to_string())
                    .collect();
            }
        }
        Vec::new()
    }

    /// Resolves the programming language for this component.
    pub fn resolved_language(&self) -> Option<String> {
        rdg_icons::detect_language(
            self.language.as_deref(),
            self.technology.as_deref(),
            &self.resolved_label(),
            self.metadata.as_deref(),
        )
        .map(|s| s.to_string())
    }

    /// Resolves the database engine for this component.
    pub fn resolved_db_type(&self) -> Option<String> {
        rdg_icons::detect_database(
            self.db_type.as_deref(),
            self.technology.as_deref(),
            &self.resolved_label(),
            &self.node_type,
        )
        .map(|s| s.to_string())
    }

    /// Resolves the technology stack / framework subtitle.
    pub fn resolved_technology(&self) -> Option<String> {
        if let Some(t) = &self.technology {
            if !t.trim().is_empty() {
                return Some(t.trim().to_string());
            }
        }
        if let Some(lang) = self.resolved_language() {
            return Some(match lang.as_str() {
                "rust" => "Rust".to_string(),
                "go" => "Go".to_string(),
                "python" => "Python".to_string(),
                "typescript" => "TypeScript".to_string(),
                "javascript" => "JavaScript".to_string(),
                "java" => "Java".to_string(),
                "kotlin" => "Kotlin".to_string(),
                "csharp" => "C#".to_string(),
                "cpp" => "C++".to_string(),
                "ruby" => "Ruby".to_string(),
                "swift" => "Swift".to_string(),
                "node" => "Node.js".to_string(),
                _ => lang,
            });
        }
        None
    }

    /// Resolves the icon key to render (language, database, user, or custom icon).
    pub fn resolved_icon(&self) -> Option<String> {
        if let Some(i) = &self.icon {
            if !i.trim().is_empty() {
                return Some(i.trim().to_ascii_lowercase());
            }
        }
        if let Some(l) = self.resolved_language() {
            return Some(l);
        }
        if let Some(db) = self.resolved_db_type() {
            return Some(db);
        }
        if let Some(p) = &self.provider {
            if let Some(icon) = rdg_icons::detect_provider(p) {
                return Some(icon.to_string());
            }
        }
        if matches!(
            self.node_type.to_ascii_lowercase().as_str(),
            "user" | "client" | "actor" | "person" | "customer"
        ) {
            return Some("user".to_string());
        }
        if matches!(
            self.node_type.to_ascii_lowercase().as_str(),
            "table" | "entity" | "record" | "schema"
        ) {
            return Some("table".to_string());
        }
        None
    }
}

// ---------------------------------------------------------------------------
// Edge definition
// ---------------------------------------------------------------------------

/// A directed edge between two nodes.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct EdgeDef {
    /// Source node ID.
    #[serde(alias = "source", alias = "src")]
    pub from: String,

    /// Target node ID.
    #[serde(alias = "target", alias = "dst")]
    pub to: String,

    /// Optional label rendered along the connector.
    #[serde(default, alias = "name", alias = "text")]
    pub label: Option<String>,

    /// Optional semantic edge style: `flow`, `async`, `error`, `data`, `bidirectional`,
    /// `sync`, `reply`, `self`, `one_to_many`, `many_to_many`, `one_to_one`, `zero_to_many`,
    /// `inheritance`, `composition`, `aggregation`, `realization`, `dependency`.
    #[serde(default, alias = "style", alias = "type")]
    pub edge_style: Option<String>,

    /// Optional flag to render bidirectional arrows.
    #[serde(default, alias = "bidir")]
    pub bidirectional: Option<bool>,

    /// Optional stroke color for the edge connector (e.g. `#ef4444`, `#0284c7`).
    #[serde(default, alias = "colour", alias = "stroke")]
    pub color: Option<String>,

    /// Optional stroke width/thickness in pixels (e.g. 1.5, 2.0).
    #[serde(default, alias = "stroke_width", alias = "thickness")]
    pub width: Option<f64>,

    /// Optional line style: `solid`, `dashed`, `dotted`.
    #[serde(
        default,
        alias = "stroke_style",
        alias = "pattern",
        alias = "style_type"
    )]
    pub line_style: Option<String>,

    /// Optional arrow head marker type: `classic`, `block`, `blockThin`, `open`, `diamond`, `oval`, `none`, `ERmany`, `ERone`, etc.
    #[serde(
        default,
        alias = "arrow_head",
        alias = "end_arrow",
        alias = "head_type",
        alias = "target_arrow"
    )]
    pub head: Option<String>,

    /// Optional arrow tail marker type: `none`, `diamond`, `oval`, `ERone`, `open`, etc.
    #[serde(
        default,
        alias = "arrow_tail",
        alias = "start_arrow",
        alias = "tail_type",
        alias = "source_arrow"
    )]
    pub tail: Option<String>,

    /// Optional explicit source port face: `top`, `bottom`, `left`, `right`.
    #[serde(default, alias = "src_port", alias = "from_port", alias = "exit_port")]
    pub source_port: Option<String>,

    /// Optional explicit target port face: `top`, `bottom`, `left`, `right`.
    #[serde(default, alias = "dst_port", alias = "to_port", alias = "entry_port")]
    pub target_port: Option<String>,

    /// Optional explicit flow sequence number (1-indexed), overriding the declaration-order
    /// auto-numbering used when the diagram sets `numbered: true`.
    #[serde(default, alias = "order", alias = "sequence")]
    pub step: Option<u32>,

    /// Optional named style preset to inherit from — see [`DiagramPayload::edge_styles`].
    #[serde(default, alias = "preset")]
    pub class: Option<String>,

    /// Optional raw draw.io style fragment appended verbatim to the computed edge style
    /// string. draw.io-only, same as [`NodeDef::style_extra`].
    #[serde(default, alias = "drawio_style", alias = "extra_style")]
    pub style_extra: Option<String>,
}

impl EdgeDef {
    /// Resolves the effective semantic edge style.
    pub fn resolved_style(&self) -> Option<String> {
        if self.bidirectional == Some(true) {
            return Some("bidirectional".to_string());
        }
        self.edge_style
            .as_deref()
            .map(|s| match s.to_ascii_lowercase().trim() {
                "sync" | "call" | "sync_call" => "sync".to_string(),
                "reply" | "return" | "response" => "reply".to_string(),
                "self" | "self_call" => "self".to_string(),
                "1..*" | "1:n" | "one_to_many" => "one_to_many".to_string(),
                "*..*" | "m:n" | "many_to_many" => "many_to_many".to_string(),
                "1..1" | "1:1" | "one_to_one" => "one_to_one".to_string(),
                "0..*" | "0:n" | "zero_to_many" => "zero_to_many".to_string(),
                "inheritance" | "extends" | "is_a" => "inheritance".to_string(),
                "realization" | "implements" => "realization".to_string(),
                "composition" => "composition".to_string(),
                "aggregation" => "aggregation".to_string(),
                "dependency" => "dependency".to_string(),
                other => other.to_string(),
            })
    }
}

// ---------------------------------------------------------------------------
// Reference YAML Template & JSON Schema
// ---------------------------------------------------------------------------

const EXAMPLE_YAML: &str = r##"# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# rdg  ·  Render Diagram Reference YAML Template
# Compile with: rdg --input diagram.yaml --output diagram.svg
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

diagram_type: architecture         # architecture | flowchart | sequence | erd | class | state
theme: standard                    # standard (elevated white cards) | dark (slate-900)
direction: tb                      # tb (top-to-bottom) | lr (left-to-right)
title: "Distributed Order Processing System"
description: "High-level service architecture, persistent storage, and event streams"
numbered: true                     # number edges 1, 2, 3... in declaration order

canvas:
  margin: 32                       # outer canvas margin in px

# Named style presets — define once, reference from any node/edge via `class:`.
# A preset only fills in fields the node/edge didn't already set explicitly.
node_styles:
  critical:
    color: "#ef4444"
    style_extra: "strokeWidth=3;"

groups:
  - id: grp_ingress
    label: "Ingress Layer"
    color: "#64748b"
    nodes: ["client", "api_gw"]

  - id: grp_core
    label: "Core Services"
    color: "#0284c7"
    nodes: ["auth_svc", "order_svc", "order_queue", "inventory_db"]

nodes:
  - id: client
    label: "Web / Mobile Client"
    type: client
    metadata: "End-user client applications"

  - id: api_gw
    label: "API Gateway"
    type: proxy
    technology: "Kong / Nginx"
    language: "lua"
    metadata: "TLS termination, auth, and rate-limiting"

  - id: auth_svc
    label: "Auth Service"
    type: service
    technology: "Go / Chi"
    language: "go"
    metadata: "OAuth2 / JWT token issuer"

  - id: order_svc
    label: "Order Service"
    type: service
    technology: "Axum 0.7"
    language: "rust"
    class: critical                # inherits the `critical` preset above
    metadata: "Core transactional order processing"

  - id: order_queue
    label: "order.events"
    type: queue
    technology: "Kafka"
    metadata: "High-throughput partitioned event stream"

  - id: inventory_db
    label: "inventory_db"
    type: database
    db_type: postgres
    technology: "PostgreSQL 16"
    fields:
      - "id: UUID [PK]"
      - "item_sku: VARCHAR [FK]"
      - "quantity: INT"
      - "updated_at: TIMESTAMP"

edges:
  - from: client
    to: api_gw
    label: "HTTPS / REST"
    edge_style: flow

  - from: api_gw
    to: auth_svc
    label: "POST /auth/verify"
    edge_style: flow

  - from: api_gw
    to: order_svc
    label: "POST /orders"
    edge_style: flow

  - from: order_svc
    to: order_queue
    label: "emit OrderPlaced"
    edge_style: async

  - from: order_svc
    to: inventory_db
    label: "SQL UPDATE"
    edge_style: data
"##;

const JSON_SCHEMA: &str = r#"{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DiagramPayload",
  "description": "Token-optimized YAML/JSON schema for rdg (Render Diagram)",
  "type": "object",
  "properties": {
    "diagram_type": {
      "type": "string",
      "enum": ["architecture", "flowchart", "sequence", "erd", "class", "state", "graph"],
      "default": "flowchart",
      "description": "Logical diagram category: architecture, flowchart, sequence, erd, class, state, graph"
    },
    "title": {
      "type": "string",
      "description": "Optional diagram title rendered as a header banner"
    },
    "description": {
      "type": "string",
      "description": "Optional diagram subtitle / description"
    },
    "theme": {
      "type": "string",
      "enum": ["standard", "dark"],
      "default": "standard",
      "description": "Visual palette: standard (elevated white cards) or dark (slate-900)"
    },
    "direction": {
      "type": "string",
      "enum": ["tb", "lr", "TB", "LR", "horizontal", "vertical"],
      "default": "tb",
      "description": "Flow direction: tb (top-to-bottom) or lr (left-to-right)"
    },
    "rank_spacing": {
      "type": "integer",
      "minimum": 10,
      "description": "Vertical gap between successive layers in pixels (default: 44)"
    },
    "node_spacing": {
      "type": "integer",
      "minimum": 10,
      "description": "Horizontal gap between sibling nodes in pixels (default: 28)"
    },
    "numbered": {
      "type": "boolean",
      "default": false,
      "description": "Number edges 1, 2, 3... in declaration order (or per-edge `step`) so a reader can trace the flow"
    },
    "canvas": {
      "type": "object",
      "description": "Canvas-level configuration",
      "properties": {
        "margin": { "type": "number", "description": "Outer canvas margin in pixels" },
        "background": { "type": "string", "description": "Canvas background color, overrides theme default" }
      }
    },
    "spacing": {
      "type": "object",
      "description": "Grouped spacing configuration (alternative to flat rank_spacing/node_spacing)",
      "properties": {
        "rank": { "type": "integer", "description": "Vertical gap between ranks in pixels" },
        "node": { "type": "integer", "description": "Horizontal gap between sibling nodes in pixels" },
        "group_gap_x": { "type": "number", "description": "Horizontal gap between group containers in pixels" },
        "group_gap_y": { "type": "number", "description": "Vertical gap between group containers in pixels" }
      }
    },
    "node_styles": {
      "type": "object",
      "description": "Named, reusable node style presets keyed by name; a node opts in via `class: <name>`",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "color": { "type": "string" },
          "technology": { "type": "string" },
          "language": { "type": "string" },
          "db_type": { "type": "string" },
          "icon": { "type": "string" },
          "width": { "type": "number" },
          "height": { "type": "number" },
          "provider": { "type": "string" },
          "style_extra": { "type": "string" }
        }
      }
    },
    "edge_styles": {
      "type": "object",
      "description": "Named, reusable edge style presets keyed by name; an edge opts in via `class: <name>`",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "edge_style": { "type": "string" },
          "color": { "type": "string" },
          "width": { "type": "number" },
          "line_style": { "type": "string" },
          "head": { "type": "string" },
          "tail": { "type": "string" },
          "style_extra": { "type": "string" }
        }
      }
    },
    "groups": {
      "type": "array",
      "description": "Visual container groups / swimlanes",
      "items": {
        "type": "object",
        "required": ["id", "label"],
        "properties": {
          "id": { "type": "string", "description": "Unique container ID" },
          "label": { "type": "string", "description": "Group title banner" },
          "color": { "type": "string", "description": "Border / accent hex color" },
          "nodes": {
            "type": "array",
            "items": { "type": "string" },
            "description": "List of node IDs enclosed inside this group"
          }
        }
      }
    },
    "nodes": {
      "type": "array",
      "description": "Ordered list of graph components / nodes",
      "items": {
        "type": "object",
        "required": ["id"],
        "properties": {
          "id": { "type": "string", "description": "Unique node identifier" },
          "label": { "type": "string", "description": "Label text with optional \\n and inline markdown" },
          "title": { "type": "string", "description": "Alternative to label: primary title line" },
          "subtitle": { "type": "string", "description": "Alternative to label: secondary muted line" },
          "type": {
            "type": "string",
            "default": "default",
            "description": "Semantic node type: service, proxy, database, table, queue, cache, function, client, decision, class, interface, abstract_class, start, end, choice"
          },
          "language": {
            "type": "string",
            "description": "Programming language for flat vector icon: rust, go, python, typescript, javascript, java, kotlin, cpp, csharp, ruby, swift"
          },
          "technology": {
            "type": "string",
            "description": "Framework or technology badge displayed below title: Axum, FastAPI, Kafka, Spring Boot, etc."
          },
          "db_type": {
            "type": "string",
            "description": "Database engine for icon: postgres, mysql, redis, mongodb, dynamodb, kafka, cassandra, sqlite, elasticsearch"
          },
          "icon": {
            "type": "string",
            "description": "Explicit icon key override (e.g. rust, postgres, redis, kafka, user)"
          },
          "color": { "type": "string", "description": "Custom accent/border color override, e.g. #ef4444" },
          "width": { "type": "number", "description": "Explicit width in pixels, skips automatic sizing" },
          "height": { "type": "number", "description": "Explicit height in pixels, skips automatic sizing" },
          "provider": { "type": "string", "enum": ["aws", "gcp", "azure"], "description": "Cloud provider hint for icon/shape selection" },
          "class": { "type": "string", "description": "Named style preset to inherit from (see node_styles)" },
          "style_extra": { "type": "string", "description": "Raw draw.io style fragment appended verbatim (draw.io only)" },
          "link": { "type": "string", "description": "URL making the rendered shape clickable (draw.io only)" },
          "fields": {
            "type": "array",
            "items": { "type": "string" },
            "description": "Structured field rows (e.g. 'id: UUID [PK]', '+execute(): void')"
          },
          "metadata": { "type": "string", "description": "Optional tooltip / annotation" }
        }
      }
    },
    "edges": {
      "type": "array",
      "description": "Directed connections between nodes",
      "items": {
        "type": "object",
        "required": ["from", "to"],
        "properties": {
          "from": { "type": "string", "description": "Source node ID (alias: source, src)" },
          "to": { "type": "string", "description": "Target node ID (alias: target, dst)" },
          "label": { "type": "string", "description": "Text rendered along connector" },
          "edge_style": {
            "type": "string",
            "enum": [
              "flow", "async", "error", "data", "bidirectional",
              "sync", "reply", "self",
              "one_to_many", "many_to_many", "one_to_one", "zero_to_many",
              "inheritance", "composition", "aggregation", "realization", "dependency"
            ],
            "default": "flow",
            "description": "Visual connector style with semantic arrowheads (ER crow's foot, UML markers, async dashed)"
          },
          "bidirectional": { "type": "boolean", "description": "Render arrows on both ends" },
          "step": { "type": "integer", "description": "Explicit flow sequence number, overrides declaration-order auto-numbering" },
          "class": { "type": "string", "description": "Named style preset to inherit from (see edge_styles)" },
          "style_extra": { "type": "string", "description": "Raw draw.io style fragment appended verbatim (draw.io only)" }
        }
      }
    }
  },
  "required": ["nodes", "edges"]
}
"#;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_YAML: &str = r#"
diagram_type: flowchart
theme: aws_light
nodes:
  - id: n1
    label: "API Gateway"
    type: proxy
  - id: n2
    label: "User Database"
    type: database
    metadata: "Stores encrypted user credentials."
edges:
  - from: n1
    to: n2
    label: "queries"
"#;

    #[test]
    fn test_round_trip_deserialization() {
        let payload = DiagramPayload::from_yaml(SAMPLE_YAML).expect("should parse");
        assert_eq!(payload.diagram_type, "flowchart");
        assert_eq!(payload.theme.as_deref(), Some("aws_light"));
        assert_eq!(payload.nodes.len(), 2);
        assert_eq!(payload.edges.len(), 1);
    }

    #[test]
    fn test_node_type_rename() {
        let payload = DiagramPayload::from_yaml(SAMPLE_YAML).expect("should parse");
        assert_eq!(payload.nodes[0].node_type, "proxy");
        assert_eq!(payload.nodes[1].node_type, "database");
    }

    #[test]
    fn test_default_node_type() {
        let yaml = r#"
diagram_type: flowchart
nodes:
  - id: n1
    label: "Plain Node"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).expect("should parse");
        assert_eq!(payload.nodes[0].node_type, "default");
    }

    #[test]
    fn test_invalid_yaml_returns_error() {
        let result = DiagramPayload::from_yaml("not: valid: yaml: {{");
        assert!(result.is_err());
    }

    #[test]
    fn test_groups_and_edge_style_deserialization() {
        let yaml = r##"
diagram_type: architecture
groups:
  - id: g1
    label: "Backend Cluster"
    color: "#eff6ff"
    nodes: ["s1", "s2"]
nodes:
  - id: s1
    label: "Service A"
  - id: s2
    label: "Service B"
edges:
  - from: s1
    to: s2
    label: "async publish"
    edge_style: async
"##;
        let payload = DiagramPayload::from_yaml(yaml).expect("should parse");
        assert_eq!(payload.groups.len(), 1);
        assert_eq!(payload.groups[0].nodes, vec!["s1", "s2"]);
        assert_eq!(payload.edges[0].edge_style.as_deref(), Some("async"));
    }

    #[test]
    fn test_aliases_and_flexible_schema() {
        let yaml = r##"
title: "Flexible Architecture"
description: "LLM-friendly aliases test"
direction: LR
rank_spacing: 50
node_spacing: 35
groups:
  - id: g1
    title: "Cluster A"
    accent: "#38bdf8"
    members: ["n1", "n2"]
nodes:
  - id: n1
    title: "API Proxy"
    subtitle: "Kong"
    shape: proxy
    description: "Routes external traffic"
  - id: n2
    label: "Main Database"
    kind: database
edges:
  - source: n1
    target: n2
    label: "sync call"
    style: flow
  - src: n2
    dst: n1
    bidirectional: true
"##;
        let payload = DiagramPayload::from_yaml(yaml).expect("should parse flexible aliases");
        assert_eq!(payload.title.as_deref(), Some("Flexible Architecture"));
        assert_eq!(
            payload.description.as_deref(),
            Some("LLM-friendly aliases test")
        );
        assert_eq!(payload.resolved_direction(), Some(Direction::LeftToRight));
        assert_eq!(payload.rank_spacing, Some(50));
        assert_eq!(payload.node_spacing, Some(35));
        assert_eq!(payload.groups[0].label, "Cluster A");
        assert_eq!(payload.groups[0].color.as_deref(), Some("#38bdf8"));
        assert_eq!(payload.groups[0].nodes, vec!["n1", "n2"]);
        assert_eq!(payload.nodes[0].node_type, "proxy");
        assert_eq!(payload.nodes[0].resolved_label(), "API Proxy\n(Kong)");
        assert_eq!(
            payload.nodes[0].metadata.as_deref(),
            Some("Routes external traffic")
        );
        assert_eq!(payload.nodes[1].node_type, "database");
        assert_eq!(payload.edges[0].from, "n1");
        assert_eq!(payload.edges[0].to, "n2");
        assert_eq!(payload.edges[0].resolved_style().as_deref(), Some("flow"));
        assert_eq!(payload.edges[1].from, "n2");
        assert_eq!(payload.edges[1].to, "n1");
        assert_eq!(
            payload.edges[1].resolved_style().as_deref(),
            Some("bidirectional")
        );
    }

    #[test]
    fn test_example_yaml_is_valid() {
        let payload = DiagramPayload::from_yaml(DiagramPayload::example_yaml())
            .expect("reference example_yaml must deserialize cleanly");
        assert_eq!(payload.nodes.len(), 6);
        assert_eq!(payload.edges.len(), 5);
        assert_eq!(payload.groups.len(), 2);
        assert!(payload.is_numbered());
        assert_eq!(payload.node_styles.len(), 1);
    }

    #[test]
    fn test_sequence_er_and_class_schema() {
        let seq_yaml = r#"
diagram_type: sequence
nodes:
  - id: client
    label: "Web Browser"
    type: participant
  - id: api
    label: "API Gateway"
    type: participant
edges:
  - from: client
    to: api
    label: "POST /login"
    style: sync
  - from: api
    to: client
    label: "200 OK (JWT)"
    style: reply
"#;
        let payload = DiagramPayload::from_yaml(seq_yaml).expect("sequence should parse");
        assert_eq!(payload.resolved_diagram_type(), "sequence");
        assert_eq!(payload.edges[0].resolved_style().as_deref(), Some("sync"));
        assert_eq!(payload.edges[1].resolved_style().as_deref(), Some("reply"));

        let er_yaml = r#"
diagram_type: er
nodes:
  - id: users
    label: "users"
    type: table
    fields:
      - "id: uuid [PK]"
      - "email: varchar [UQ]"
  - id: orders
    label: "orders\n---\nid: uuid [PK]\nuser_id: uuid [FK]"
    type: table
edges:
  - from: users
    to: orders
    style: one_to_many
"#;
        let er_payload = DiagramPayload::from_yaml(er_yaml).expect("ER should parse");
        assert_eq!(er_payload.resolved_diagram_type(), "er");
        assert_eq!(er_payload.nodes[0].resolved_fields().len(), 2);
        assert_eq!(er_payload.nodes[1].resolved_fields().len(), 2);
        assert_eq!(
            er_payload.edges[0].resolved_style().as_deref(),
            Some("one_to_many")
        );
    }

    // -----------------------------------------------------------------------
    // Phase A: style presets, escape hatches, canvas/spacing, numbering
    // -----------------------------------------------------------------------

    #[test]
    fn test_node_style_preset_fills_gaps_but_not_explicit_fields() {
        let yaml = r##"
node_styles:
  critical:
    color: "#ef4444"
    technology: "Preset Tech"
    style_extra: "strokeWidth=3;"
nodes:
  - id: n1
    label: "A"
    class: critical
  - id: n2
    label: "B"
    class: critical
    color: "#000000"
edges: []
"##;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        let n1 = payload.effective_node(&payload.nodes[0]);
        assert_eq!(n1.color.as_deref(), Some("#ef4444"));
        assert_eq!(n1.technology.as_deref(), Some("Preset Tech"));
        assert_eq!(n1.style_extra.as_deref(), Some("strokeWidth=3;"));

        // n2 explicitly set color, so the preset must not override it.
        let n2 = payload.effective_node(&payload.nodes[1]);
        assert_eq!(n2.color.as_deref(), Some("#000000"));
        assert_eq!(n2.technology.as_deref(), Some("Preset Tech"));
    }

    #[test]
    fn test_unknown_style_class_is_a_no_op() {
        let yaml = r#"
nodes:
  - id: n1
    label: "A"
    class: does_not_exist
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        let n1 = payload.effective_node(&payload.nodes[0]);
        assert_eq!(n1.color, None);
    }

    #[test]
    fn test_edge_style_preset_resolution() {
        let yaml = r##"
edge_styles:
  hot_path:
    edge_style: async
    color: "#f97316"
nodes:
  - id: n1
    label: "A"
  - id: n2
    label: "B"
edges:
  - from: n1
    to: n2
    class: hot_path
"##;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        let e = payload.effective_edge(&payload.edges[0]);
        assert_eq!(e.edge_style.as_deref(), Some("async"));
        assert_eq!(e.color.as_deref(), Some("#f97316"));
    }

    #[test]
    fn test_canvas_and_spacing_config_parse() {
        let yaml = r##"
canvas:
  margin: 40
  background: "#111111"
spacing:
  rank: 70
  node: 30
  group_gap_x: 80
  group_gap_y: 90
numbered: true
nodes:
  - id: n1
    label: "A"
edges: []
"##;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        assert!(payload.is_numbered());
        let canvas = payload.canvas.expect("canvas should parse");
        assert_eq!(canvas.margin, Some(40.0));
        assert_eq!(canvas.background.as_deref(), Some("#111111"));
        let spacing = payload.spacing.expect("spacing should parse");
        assert_eq!(spacing.rank, Some(70));
        assert_eq!(spacing.node, Some(30));
        assert_eq!(spacing.group_gap_x, Some(80.0));
        assert_eq!(spacing.group_gap_y, Some(90.0));
    }

    #[test]
    fn test_numbered_defaults_false() {
        let payload = DiagramPayload::default();
        assert!(!payload.is_numbered());
    }

    #[test]
    fn test_node_width_height_provider_link_style_extra() {
        let yaml = r#"
nodes:
  - id: n1
    label: "Lambda"
    type: function
    provider: aws
    width: 200
    height: 80
    style_extra: "opacity=60;"
    link: "https://example.com"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        let n = &payload.nodes[0];
        assert_eq!(n.provider.as_deref(), Some("aws"));
        assert_eq!(n.width, Some(200.0));
        assert_eq!(n.height, Some(80.0));
        assert_eq!(n.style_extra.as_deref(), Some("opacity=60;"));
        assert_eq!(n.link.as_deref(), Some("https://example.com"));
    }

    #[test]
    fn test_edge_step_override() {
        let yaml = r#"
nodes:
  - id: n1
    label: "A"
  - id: n2
    label: "B"
edges:
  - from: n1
    to: n2
    step: 5
"#;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        assert_eq!(payload.edges[0].step, Some(5));
    }

    // -----------------------------------------------------------------------
    // Phase G: edge cases
    // -----------------------------------------------------------------------

    #[test]
    fn test_unicode_and_emoji_labels_round_trip() {
        let yaml = r#"
nodes:
  - id: n1
    label: "支付服务 💳 → Ürün Servisi"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        assert_eq!(payload.nodes[0].label, "支付服务 💳 → Ürün Servisi");
        assert_eq!(
            payload.nodes[0].resolved_label(),
            "支付服务 💳 → Ürün Servisi"
        );
    }

    #[test]
    fn test_very_long_unbroken_label_does_not_panic() {
        let long_word = "a".repeat(5000);
        let payload = DiagramPayload {
            nodes: vec![NodeDef {
                id: "n1".into(),
                label: long_word.clone(),
                ..Default::default()
            }],
            ..Default::default()
        };
        assert_eq!(payload.nodes[0].resolved_label(), long_word);
    }

    #[test]
    fn test_unknown_top_level_keys_are_ignored_not_errors() {
        let yaml = r#"
this_key_does_not_exist: true
another_bogus_field:
  nested: 1
nodes:
  - id: n1
    label: "A"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).expect("unknown keys must not error");
        assert_eq!(payload.nodes.len(), 1);
    }

    #[test]
    fn test_zero_and_negative_spacing_values_parse() {
        // The schema itself doesn't clamp — it's the layout engine's job to behave sanely
        // with degenerate config; the schema layer should at least not reject the input.
        let yaml = r#"
rank_spacing: 0
node_spacing: 0
nodes:
  - id: n1
    label: "A"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).unwrap();
        assert_eq!(payload.rank_spacing, Some(0));
        assert_eq!(payload.node_spacing, Some(0));
    }

    #[test]
    fn test_missing_required_node_id_is_an_error() {
        let yaml = r#"
nodes:
  - label: "No id field"
edges: []
"#;
        assert!(DiagramPayload::from_yaml(yaml).is_err());
    }

    #[test]
    fn test_empty_nodes_and_edges_is_valid() {
        let payload = DiagramPayload::from_yaml("nodes: []\nedges: []\n").unwrap();
        assert!(payload.nodes.is_empty());
        assert!(payload.edges.is_empty());
    }
}
