[package]
name = "rdg-render-svg"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "SVG rendering backend for rdg."

[dependencies]
rdg-graph = { workspace = true }
rdg-layout = { workspace = true }
rdg-icons = { workspace = true }
rdg-render-core = { workspace = true }
anyhow = { workspace = true }
quick-xml = { workspace = true }
petgraph = { workspace = true }

[dev-dependencies]
rdg-schema = { workspace = true }
