//! `rdg` (Render Diagram) — deterministic LLM diagram compilation engine.
//!
//! This crate provides a pipeline that converts a token-optimised YAML semantic
//! graph (as generated by an LLM) into a perfectly-routed draw.io XML or SVG
//! diagram, using deterministic graph layout algorithms.
//!
//! # Pipeline
//!
//! ```text
//! YAML payload ──► schema::DiagramPayload
//!                       │
//!                       ▼
//!                 graph::CompiledGraph  (petgraph StableDiGraph + FAS cycle breaking)
//!                       │
//!                       ▼
//!                 layout::LayoutResult  (layout-rs Sugiyama / topo-sort fallback)
//!                       │
//!              ┌─────────────────┐
//!              ▼                 ▼
//!        render_drawio       render_svg
//!        (.drawio XML)       (.svg)
//! ```
//!
//! # Crate structure
//!
//! | Module | Responsibility |
//! |--------|---------------|
//! | [`schema`] | Serde structs for the YAML input |
//! | [`graph`]  | petgraph construction + cycle breaking |
//! | [`layout`] | Spatial layout via layout-rs |
//! | [`render`] | draw.io XML and SVG serialisation |

pub mod graph;
pub mod layout;
pub mod render;
pub mod schema;

pub use anyhow::Result;
