//! Input schema for the token-optimized YAML payload generated by an LLM.
//!
//! The LLM emits a flat, minimal YAML document. This module defines the
//! corresponding serde structs and provides a [`DiagramPayload::from_yaml`]
//! constructor that validates the input at the boundary.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Top-level diagram payload
// ---------------------------------------------------------------------------

/// Root structure of the token-optimized YAML payload produced by an LLM.
///
/// # Example
///
/// ```yaml
/// diagram_type: flowchart
/// theme: aws_light
/// nodes:
///   - id: n1
///     label: "API Gateway"
///     type: proxy
///   - id: n2
///     label: "User Database"
///     type: database
///     metadata: "Stores encrypted user credentials."
/// edges:
///   - from: n1
///     to: n2
///     label: "queries"
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DiagramPayload {
    /// Logical diagram category (e.g. `flowchart`, `sequence`, `uml`).
    pub diagram_type: String,

    /// Optional theme override. When absent the CLI `--theme` flag takes precedence.
    #[serde(default)]
    pub theme: Option<String>,

    /// Optional flow direction override: `tb` (top-to-bottom) or `lr` (left-to-right).
    #[serde(default)]
    pub direction: Option<String>,

    /// Ordered list of node definitions.
    #[serde(default)]
    pub nodes: Vec<NodeDef>,

    /// Ordered list of directed edge definitions.
    #[serde(default)]
    pub edges: Vec<EdgeDef>,

    /// Optional list of visual group / swimlane containers.
    #[serde(default)]
    pub groups: Vec<GroupDef>,
}

impl DiagramPayload {
    /// Parse a YAML string into a [`DiagramPayload`].
    ///
    /// # Errors
    ///
    /// Returns an error if the YAML is malformed or does not match the schema.
    pub fn from_yaml(input: &str) -> Result<Self> {
        serde_yaml::from_str(input).context("failed to deserialize YAML diagram payload")
    }
}

// ---------------------------------------------------------------------------
// Group / Swimlane definition
// ---------------------------------------------------------------------------

/// Visual container grouping a set of related nodes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GroupDef {
    /// Unique identifier for the group container.
    pub id: String,

    /// Label displayed in the group header.
    pub label: String,

    /// Optional accent color for container background/border (e.g. `#eff6ff`).
    #[serde(default)]
    pub color: Option<String>,

    /// List of node IDs contained in this group.
    #[serde(default)]
    pub nodes: Vec<String>,
}

// ---------------------------------------------------------------------------
// Node definition
// ---------------------------------------------------------------------------

/// A single semantic node as emitted by the LLM.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NodeDef {
    /// Unique identifier used to reference this node in edges.
    pub id: String,

    /// Human-readable label rendered inside the shape.
    pub label: String,

    /// Semantic type used to select the draw.io style (e.g. `proxy`, `database`).
    #[serde(rename = "type", default = "default_node_type")]
    pub node_type: String,

    /// Optional free-text metadata (e.g. tooltip, annotation).
    #[serde(default)]
    pub metadata: Option<String>,
}

fn default_node_type() -> String {
    "default".to_owned()
}

// ---------------------------------------------------------------------------
// Edge definition
// ---------------------------------------------------------------------------

/// A directed edge between two nodes.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeDef {
    /// Source node ID.
    pub from: String,

    /// Target node ID.
    pub to: String,

    /// Optional label rendered along the connector.
    #[serde(default)]
    pub label: Option<String>,

    /// Optional semantic edge style: `flow`, `async`, `error`, `data`, `bidirectional`.
    #[serde(default)]
    pub edge_style: Option<String>,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE_YAML: &str = r#"
diagram_type: flowchart
theme: aws_light
nodes:
  - id: n1
    label: "API Gateway"
    type: proxy
  - id: n2
    label: "User Database"
    type: database
    metadata: "Stores encrypted user credentials."
edges:
  - from: n1
    to: n2
    label: "queries"
"#;

    #[test]
    fn test_round_trip_deserialization() {
        let payload = DiagramPayload::from_yaml(SAMPLE_YAML).expect("should parse");
        assert_eq!(payload.diagram_type, "flowchart");
        assert_eq!(payload.theme.as_deref(), Some("aws_light"));
        assert_eq!(payload.nodes.len(), 2);
        assert_eq!(payload.edges.len(), 1);
    }

    #[test]
    fn test_node_type_rename() {
        let payload = DiagramPayload::from_yaml(SAMPLE_YAML).expect("should parse");
        assert_eq!(payload.nodes[0].node_type, "proxy");
        assert_eq!(payload.nodes[1].node_type, "database");
    }

    #[test]
    fn test_default_node_type() {
        let yaml = r#"
diagram_type: flowchart
nodes:
  - id: n1
    label: "Plain Node"
edges: []
"#;
        let payload = DiagramPayload::from_yaml(yaml).expect("should parse");
        assert_eq!(payload.nodes[0].node_type, "default");
    }

    #[test]
    fn test_invalid_yaml_returns_error() {
        let result = DiagramPayload::from_yaml("not: valid: yaml: {{");
        assert!(result.is_err());
    }

    #[test]
    fn test_groups_and_edge_style_deserialization() {
        let yaml = r##"
diagram_type: architecture
groups:
  - id: g1
    label: "Backend Cluster"
    color: "#eff6ff"
    nodes: ["s1", "s2"]
nodes:
  - id: s1
    label: "Service A"
  - id: s2
    label: "Service B"
edges:
  - from: s1
    to: s2
    label: "async publish"
    edge_style: async
"##;
        let payload = DiagramPayload::from_yaml(yaml).expect("should parse");
        assert_eq!(payload.groups.len(), 1);
        assert_eq!(payload.groups[0].nodes, vec!["s1", "s2"]);
        assert_eq!(payload.edges[0].edge_style.as_deref(), Some("async"));
    }
}
